apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: frontend-backend-config
  namespace: staging-frontend
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false